### ISSUE TITLE
Combine multiple netcdf files containing multiple variables 

### ISSUE THREAD

**Issue by IssamHu** [mdsumner/ncdf4#2]
Dear Sir,
Please can you advice me how to combine the attached netcdf argo files contaning multiple variables into a single netcdf file gathering all the data?

[argo_download (15).tar.gz](https://github.com/mdsumner/ncdf4/files/4373644/argo_download.15.tar.gz)

**Comment by mdsumner** [comment]
No, I cannot sorry. This project is only a fork of the ncdf4 package while I figured something out. Best of luck with it
